### ISSUE TITLE
autokeras time

### ISSUE THREAD

**Issue by amrrs** [minsuk-heo/deeplearning#1]
Hi, Thanks for the video you put and the notebook. Did `autokeras` really take 5 hours on your machine?

Would you be okay to share the specs of your machine? On my machine it was running forever so i had to stop.

**Comment by minsuk-heo** [comment]
If you see my notebook,
I put 5*60*60 in the code for time limit, otherwise it will run 24 hours.
Be sure you put time limit :)

Best,
Minsuk

**Comment by amrrs** [comment]
Yes i changed it now for 10 minutes, got a less accuracy but at least Yeah, my code ran successfully :) 

Thanks for the tutorial. I'll close this issue happily!

**Comment by minsuk-heo** [comment]
Cool!
